In [2]:
#! /usr/bin/python3

from numpy import *

import matplotlib.pyplot as plt # from pylab import plot,show
from matplotlib.pyplot import figure

import warnings
warnings.filterwarnings("ignore")


#problema 1

print ("")
print("###############")
print ("")
print("Ejercicio 1:")


### MÉTODO DE SOLUCIóN BACKWARD ###

M11=array([(1.0,2.0,1.0),
          (0.0,-4.0,1.0),
          (0.0,0.0,-2.0)])
         
M12=array([5.0,2.0,4.0])


def sust_inv(M,N):
    rangoM = len(M)
    x = zeros(rangoM)  #se inicia matriz x
    for i in range(rangoM-1,-1, -1):   #se hace conteo inverso
            temp = N[i]
            for k in range(rangoM-1,i, -1):
                temp -= M[i][k]*x[k]
            x[i] = temp/M[i][i] 
    return (x)


print ("")
print ("### MÉTODO DE SOLUCIóN BACKWARD ###")
print ("Sean las matrices del problema:")
print ("A=")
print (M11)
print ("B=")    
print (M12)          
print ("Por sustitución backward obtenemos los siguientes resultados para")
print ("[x1, x2, x3]")
print (sust_inv(M11,M12))  


### MÉTODO DE SOLUCIóN FORWARD ###

M21=array([(2.0,0.0,0.0),
          (2.0,4.0,0.0),
          (4.0,3.0,3.0)])
         
M22=array([4.0,2.0,5.0])
print ("")
print ("### MÉTODO DE SOLUCIóN FORWARD ###")
print ("Sean las matrices del problema:")
print ("A=")
print (M21)
print ("B=")    
print (M22)          
print ("Por sustitución forward obtenemos los siguientes resultados para")
print ("[x1, x2, x3]")
print (sust_inv(M21,M22)) 

#problema 2

print ("")
print("###############")
print ("")
print("Ejercicio 2:")

#nro_resist = input("Ingrese el número de resistencias N= ")

#para el ejercicios ingresamos N manualmente

M=6

#generando la matriz para N resistencias con R=1 Ohm

V=zeros([N,N])

#luego de hacer las ecuaciones vemos un patrón repetitivo
#los enunciamos para agregarlos facilmente

patron_1 = [3,-1,-1]
patron_2 = [-1,4,-1,-1] 
patron_k = [-1,-1,4,-1,-1] 
patron_1n = [-1,-1,4,-1]
patron_n = [-1,-1,3]


# creando la matriz A(N,N)
for i in range(0,N,1):
    if i == 0 :             #para llenar la primera linea de 0s
        for j in range (N-3):  # = N - len(patron_1)
            patron_1.append(0)    #agrego 0 hasta que concuerde con el rango
        V[0]=patron_1
    if i == 1 :
        for j in range (N-4): # = N - len(patron_2)
            patron_2.append(0)    #agrego 0 hasta que concuerde con el rango
        V[1]=patron_2
    if i > 1 :
        if i < N-2 :
            temp = []
            for j in range (i-2):  #lleno lo ceros necesarios al inicio de esta fila                
                temp.append(0)
            for j in range (0,5,1): #agregando los valores de patron_k a temp, 5 = len(patron_k)
                elem_k = patron_k[j]
                temp.append(elem_k)
            rangito = len(temp)     # i+1+len(patron_k)
            if rangito < N:
                for j in range (rangito-1,N-1): #añado lo ceros faltantes hasta concordar con el rango
                        temp.append(0)
            V[i]=temp
        if i == N-2 :     #pues la linea N-1 muestra un patrón único, N-1 <> N-2 por i empezar en 0
                temp = []
                for j in range (N-4): # = N - len(patron_1n)
                    temp.append(0)  #lleno lo ceros necesarios al inicio de esta fila
                for j in range (0,4,1): #agregando los valores de patron_1n a temp, 4 = len(patron_1n)
                    elem_1n = patron_1n[j]
                    temp.append(elem_1n)
                V[i]=temp
        if i == N-1 :  #pues N también muestra un patrón único
                temp = []
                for j in range (N-3): # = N - len(patron_n)
                    temp.append(0)  #lleno lo ceros necesarios al inicio de esta fila
                for j in range (0,3,1): #agregando los valores de patron_1n a temp, 3 = len(patron_n)
                    elem_n = patron_n[j]
                    temp.append(elem_n) 
                V[i]=temp

#creando matriz B(N,1)
temp=[5,5] #valores inmovibles que se encontraron en las eqs
for i in range(N-2):
        temp.append(0)
B=temp
        
                
                
#crear funcion creando_matriz /intentarlo en otro notebook

def Descomp_Cholesky(M,N):
    dim_M = M.shape
    rangoM = len(M)
    g = zeros(dim_M)
    for i in range(0,rangoM, 1):
        temp = 0
        for k in range(0,i,1):     #buscamos la raiz pedida
            temp = temp + g[k][i]**2
        g[i][i] = sqrt(M[i, i] - temp)
        for j in range(i+1,rangoM, 1):
            temp = 0
            for k in range(0,i,1):
                temp = temp + g[k][i]*g[k][j]
            g[i, j] = (M[i][j]-temp)/g[i][i]
    
    print ("")
    print ("Sea la matriz G para la descomposicion de Cholesky:") 
    print (g)
    print ("y sea su transpuesta:") 
    print (g.T)
    
    # se busca la matriz d por sustitucion forward
    d = []  #inicio la matriz d
    trans_g= g.T   #transpuesta de g
    rangoN = len(N)
    for i in range(rangoN):
        temp = 0
        d.append(N[i])
        for j in range(i):
            temp = temp + trans_g[i, j]*d[j]
        d[i] = (N[i] - temp)/trans_g[i, i]
    print("")
    print ("encontrandose la matriz d: ")    
    print(d)
    
    #se busca la matriz x, por sustitucion backwards
    x = zeros(rangoM) #se inicia array para los valores de la matriz d
    for i in range(rangoM-1,-1, -1):   #se hace conteo inverso
            temp = d[i]
            for k in range(rangoM-1,i, -1):
                temp -= g[i][k]*x[k]
            x[i] = temp/g[i][i]  
    print ("")
    print ("se encuentra la matriz x:") 
    return (x)

def Descomp_LU(M,N):
    
    #hallamos las matrices L y U

    dim_M = M.shape
    rangoM = len(M)
    L = zeros(dim_M) #inicio matriz L con tamaño dim_M=(rangoM,rangoM) por ser M cuadrada
    U = zeros(dim_M) #inicio U
    for i in range(rangoM):
        L[i,i] = 1.0    #llena la diagonal de L de 1's
        for j in range(i+1,rangoM):
            L[j,i] = M[j,i]/M[i,i]  #Genera la fila j de la matriz
            for k in range(i+1,rangoM):
                M[j,k] = M[j,k] - L[j,i]*M[i,k]
        for k in range(i,rangoM):
            U[i,k] = M[i,k]  #genera la fila i de la matriz U
    print("matrices L y  U respectivamente")
    print("L=")
    print(L)
    print("")
    print("U=")
    print(U)
    print("")
    
    #obtenemos la matriz d (de la eq Ld = b)
    #para esta funcion: b = N
    #usamos la sustitución forward 
    
    d = []  #inicio la matriz d
    rangoN = len(N)
    for i in range(rangoN):
        temp = 0
        d.append(N[i])
        for j in range(i):
            temp = temp + L[i, j]*d[j]
        d[i] = (N[i] - temp)/L[i, i]
    print("")
    print ("encontrandose la matriz d: _de la eq Ld = b_")    
    print(d)
    
    
    #obtenida d, hallamos x (de la eq Ux = d)
    #usamos sustitución backwards/sust_inv del ejercicio anterior
    
    x = zeros(rangoM)  #se inicia matriz x
    for i in range(rangoM-1,-1, -1):   #se hace conteo inverso
            temp = d[i]
            for k in range(rangoM-1,i, -1):
                temp -= U[i][k]*x[k]
            x[i] = temp/U[i][i]  
    print ("")
    print ("encontrandose la matriz x: _de la eq Ux = d_") 
    return (x)
    

print("Sea la matriz del sistema para N=6")                
print (V)
print (B)
print("###  ###")
print(Descomp_Cholesky(V,B))
print("###  ###")
print("DESCOMPOSICION LU")
print ("")
print(Descomp_LU(V,B))
print ("siendo estas las soluciones")
print ("")


###############

Ejercicio 1:

### MÉTODO DE SOLUCIóN BACKWARD ###
Sean las matrices del problema:
A=
[[ 1.  2.  1.]
 [ 0. -4.  1.]
 [ 0.  0. -2.]]
B=
[5. 2. 4.]
Por sustitución backward obtenemos los siguientes resultados para
[x1, x2, x3]
[ 9. -1. -2.]

### MÉTODO DE SOLUCIóN FORWARD ###
Sean las matrices del problema:
A=
[[2. 0. 0.]
 [2. 4. 0.]
 [4. 3. 3.]]
B=
[4. 2. 5.]
Por sustitución forward obtenemos los siguientes resultados para
[x1, x2, x3]
[2.         0.5        1.66666667]

###############

Ejercicio 2:


NameError: name 'N' is not defined

In [6]:
a= [(1,2),(5,6)]
b= [3,4]
print(a+b)

[(1, 2), (5, 6), 3, 4]


In [6]:
#Sean las matrices del problema

def Descomp_LU(M,N):
    
    #hallamos las matrices L y U

    dim_M = M.shape
    rangoM = len(M)
    L = zeros(dim_M) #inicio matriz L con tamaño dim_M=(rangoM,rangoM) por ser M cuadrada
    U = zeros(dim_M) #inicio U
    for i in range(rangoM):
        L[i,i] = 1.0    #llena la diagonal de L de 1's
        for j in range(i+1,rangoM):
            L[j,i] = M[j,i]/M[i,i]  #Genera la fila j de la matriz
            for k in range(i+1,rangoM):
                M[j,k] = M[j,k] - L[j,i]*M[i,k]
        for k in range(i,rangoM):
            U[i,k] = M[i,k]  #genera la fila i de la matriz U
    print("matrices L y  U respectivamente")
    print("L=")
    print(L)
    print("")
    print("U=")
    print(U)
    print("")
    
    #obtenemos la matriz d (de la eq Ld = b)
    #para esta funcion: b = N
    #usamos la sustitución forward 
    
    d = []  #inicio la matriz d
    rangoN = len(N)
    for i in range(rangoN):
        temp = 0
        d.append(N[i])
        for j in range(i):
            temp = temp + L[i, j]*d[j]
        d[i] = (N[i] - temp)/L[i, i]
    print("")
    print ("encontrandose la matriz d: _de la eq Ld = b_")    
    print(d)
    
    
    #obtenida d, hallamos x (de la eq Ux = d)
    #usamos sustitución backwards/sust_inv del ejercicio anterior
    
    x = zeros(rangoM)  #se inicia matriz x
    for i in range(rangoM-1,-1, -1):   #se hace conteo inverso
            temp = d[i]
            for k in range(rangoM-1,i, -1):
                temp -= U[i][k]*x[k]
            x[i] = temp/U[i][i]  
    print ("")
    print ("encontrandose la matriz x: _de la eq Ux = d_") 
    return (x)
    

A =array([(30.,-20.,0),
    (20.,40.,-20.),
    (0,-10.,10.)])

#usando g=9.8m/s2
B = [9.8,9.8,9.8]

print(A.shape)
#usando factorizacion LU, se obtiene
print("")
print("DESCOMPOSICION LU")
print ("")
# print(Descomp_LU(A,B))
print("= [V1 V2 V3 ... V100]")
print ("siendo estas las soluciones para los voltajes")
print ("")


(3, 3)

DESCOMPOSICION LU

= [V1 V2 V3 ... V100]
siendo estas las soluciones para los voltajes

